version: '3'
services:
  agent:
    build: ./agent
    environment:
      - DD_API_KEY
  web:
    build: .
    ports:
      - "127.0.0.1:8000:8080"
    depends_on:
      - agent
      - suggestions.service.us-east-1.consul
  suggestions.service.us-east-1.consul:
    build: ./suggestions
    command: flask run --port=5001 --host=0.0.0.0
    volumes:
      - "./suggestions:/app"
    environment:
      - FLASK_APP=suggestions.py
      - FLASK_DEBUG=1
    depends_on:
      - agent
