version: '3'
services:
  agent:
    image: "datadog/docker-dd-agent:latest"
    environment:
      - DD_API_KEY
  web:
    build: .
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - agent
      - taster
  taster:
    environment:
      - FLASK_APP=taster.py
      - FLASK_DEBUG=1
    build: ./taster
    command: flask run --port=5001 --host=0.0.0.0
    volumes:
      - "./taster:/app"
    depends_on:
      - agent
